keyservice/api/urls.py
from django.urls import path
from .views import PositionListApiView, MapPositionListApiView


urlpatterns = [
    path("get-positions/", PositionListApiView.as_view(), name="get-positions"),
    path("get-map-positions/", MapPositionListApiView.as_view(), name="get-map-positions"),
]

seotool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from keyservice.admin import admin_site
from keyservice.views import (
    index,
    get_position,
    get_report,
    upload_file,
    upload_file_map,
    delete_positions,
    get_cities,
    get_last_record,
    get_map_position,
    get_graph_report,
    get_urls_from_keyword,
    test_from,
)
from keyservice.api.views import GoogleKeywordIdea, signin, user_info, PositionListApiView
from suggestion.views import suggestion_service
from suggestion.api.views import BarcodeApiView
from jobservice.views import JobListView

urlpatterns = [
    # Admin urls
    path("admin/", admin_site.urls),
    # main urls
    path("", index, name="index"),
    path("search/", get_position, name="search"),
    path("map-search/", get_map_position, name="map-search"),
    path("report/", get_report, name="report"),
    path("graph-report/", get_graph_report, name="graph-report"),
    path("upload/", upload_file, name="upload"),
    path("map_upload",upload_file_map, name="map_upload"),
    path("delete/", delete_positions, name="delete"),
    path("suggestion/", suggestion_service, name="key-suggestion"),
    path("key-to-url/", get_urls_from_keyword, name="keyword-to-url"),
    path("test/", test_from, name="test-from"),
    path("job-list/", JobListView.as_view(), name="job-list"),
    path(
        "loading/", TemplateView.as_view(template_name="keyservice/loading.html"), name="loading",
    ),
    # Sub urls
    path("get-cities", get_cities, name="get-cities"),
    path("get-last-record", get_last_record, name="last-record"),
    # Api urls
    path("barcode/", BarcodeApiView.as_view(), name="barcode"),
    path("keyword-idea", GoogleKeywordIdea.as_view(), name="google-keyword-idea"),
    path("signin", signin, name="signin"),
    path("token-info", user_info, name="token-info"),
    path("api/", include("keyservice.api.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

keyservice/forms.py
from django import forms
from .models import Keyword, City


class SearchForm(forms.Form):
    site = forms.ModelChoiceField(queryset=Keyword.objects.all())
    cities = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, queryset=City.objects.all(), required=False
    )


class MapSearchForm(forms.Form):
    site = forms.ModelChoiceField(queryset=Keyword.objects.all())


class ReportForm(forms.Form):
    site = forms.ModelChoiceField(queryset=Keyword.objects.all())
    date = forms.DateField(
        localize=True,
        widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
    )
    is_map = forms.BooleanField(required=False)


class GraphReportForm(forms.Form):
    INTERVAL_CHOICES = (
        ("1", "One Month"),
        ("3", "Three Month"),
        ("6", "Six Month"),
        ("12", "One Year"),
    )
    site = forms.ModelChoiceField(queryset=Keyword.objects.all())
    interval = forms.ChoiceField(choices=INTERVAL_CHOICES)


class UploadFileForm(forms.Form):
    file = forms.FileField()


class KeywordToUrlFrom(forms.Form):
    keyword = forms.CharField(max_length=100)
    url_text = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 10, "cols": 60}),
        required=False,
        label="URL Text",
    )

keyservice/api/views.py
import logging
from datetime import datetime
from django.contrib.auth import authenticate
from rest_framework.authtoken.models import Token
from rest_framework.views import APIView
from rest_framework.generics import ListAPIView
from rest_framework.response import Response
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.decorators import api_view, permission_classes
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST, HTTP_404_NOT_FOUND
from .google_keyword_idea_service import SearchVolumePuller
from .serializers import (
    UserSigninSerializer,
    UserSerializer,
    PositionSerializer,
    MapPositionSerializer,
)
from .authentication import token_expire_handler, expires_in
from ..models import Position, MapPosition


logger = logging.getLogger(__name__)


class GoogleKeywordIdea(APIView):
    authentication_classes = [TokenAuthentication]

    def post(self, request, format=None):
        query = request.data.get("query")
        msg = f"Query: {query}"
        logger.debug(msg)
        logger.debug("Hey there it works!!")
        data = SearchVolumePuller.get_google_service(query)
        return Response({"data": data})


@api_view(["POST"])
@permission_classes((AllowAny,))  # here we specify permission by default we set IsAuthenticated
def signin(request):
    signin_serializer = UserSigninSerializer(data=request.data)
    if not signin_serializer.is_valid():
        return Response(signin_serializer.errors, status=HTTP_400_BAD_REQUEST)

    user = authenticate(
        username=signin_serializer.data["username"], password=signin_serializer.data["password"]
    )
    if not user:
        return Response(
            {"detail": "Invalid Credentials or activate account"}, status=HTTP_404_NOT_FOUND
        )

    # TOKEN STUFF
    token, _ = Token.objects.get_or_create(user=user)

    # token_expire_handler will check, if the token is expired it will generate new one
    is_expired, token = token_expire_handler(token)  # The implementation will be described further
    user_serialized = UserSerializer(user)

    return Response(
        {"user": user_serialized.data, "expires_in": expires_in(token), "token": token.key},
        status=HTTP_200_OK,
    )


@api_view(["GET"])
def user_info(request):
    return Response(
        {"user": request.user.username, "expires_in": expires_in(request.auth)}, status=HTTP_200_OK
    )


class PositionListApiView(ListAPIView):
    # queryset = Position.objects.all()
    serializer_class = PositionSerializer
    permission_classes = (IsAuthenticated,)
    # user = authenticate(
        # username=serializer_class.data["username"], password=serializer_class.data["password"]
    # )
    # if not user:
    #     return Response(
    #         {"detail": "Invalid Credentials or activate account"}, status=HTTP_404_NOT_FOUND
    #     )
    # token, _ = Token.objects.get_or_create(user=user)

    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        serializer = PositionSerializer(queryset, many=True)
        return Response(serializer.data)

    def get_queryset(self):
        queryset = Position.objects.all()
        url = self.request.query_params.get("url", None)
        date = self.request.query_params.get("date", None)
        if url is not None:
            queryset = queryset.filter(url=url)
        if date is not None:
            d = datetime.strptime(date, "%Y-%m-%d")
            queryset = queryset.filter(date__month=d.month)
        return queryset.filter(verified=True)


class MapPositionListApiView(ListAPIView):
    queryset = MapPosition.objects.all()
    serializer_class = MapPositionSerializer
    permission_classes = (IsAuthenticated,)
    # token, _ = Token.objects.get_or_create(user=user)

    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        serializer = MapPositionSerializer(queryset, many=True)
        return Response(serializer.data)

    def get_queryset(self):
        queryset = MapPosition.objects.all()
        name = self.request.query_params.get("name", None)
        date = self.request.query_params.get("date", None)
        if name is not None:
            queryset = queryset.filter(name=name)
        if date is not None:
            d = datetime.strptime(date, "%Y-%m-%d")
            queryset = queryset.filter(date__month=d.month)
        return queryset.filter(verified=True)

keyservice/views.py
import os
import csv
import time
import random
from datetime import date, datetime, timedelta
from django.shortcuts import render
from django.views.static import serve
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from .models import Keyword, City, Position, MapPosition, KeywordCityRel
from .service import get_result, get_map_result, handle_uploaded_file, map_upload, google
from .graph_report import generate_graph
from .forms import (
    UploadFileForm,
    KeywordToUrlFrom,
    SearchForm,
    MapSearchForm,
    ReportForm,
    GraphReportForm,
)
from .utils import (
    _keywords_to_positions,
    _get_graph_record,
    _get_map_records,
    _get_map_record,
    _get_record,
    _get_search_records,
    _check_map_record,
)

CUR_DIR = os.path.dirname(os.path.abspath(__file__))
PAR_DIR = os.path.normpath(os.path.join(CUR_DIR, os.pardir))


def index(request, *args, **kwargs):
    positions = Position.objects.filter(date=date.today())
    if positions is not None and positions.count() != 0:
        # print(positions)
        return render(request, "keyservice/index.html", {"positions": positions, "status": True})
    else:
        return render(request, "keyservice/index.html", {})


def get_position(request, *args, **kwargs):
    all_pos, error = [], ""
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            keyword = form.cleaned_data["site"]
            cities = form.cleaned_data["cities"]

            priority_keyword = keyword.priority_keyword.split(",")
            main_keyword = (
                keyword.main_keyword.split(",") if len(keyword.main_keyword.strip()) > 0 else []
            )
            secondary_keywords = keyword.secondary_keyword.split(",")
            keys = priority_keyword + main_keyword
            all_pos = _keywords_to_positions(keys, secondary_keywords, cities, keyword)
        return render(request, "keyservice/result.html", {"positions": all_pos, "error": error},)
    else:
        form = SearchForm()
        return render(request, "keyservice/search.html", {"form": form})


def get_map_position(request, *args, **kwargs):
    all_pos, temp, error, seq = [], [], "", 0

    if request.method == "POST":
        form = MapSearchForm(request.POST)
        if form.is_valid():
            keyword = form.cleaned_data["site"]
            keywordcitys = KeywordCityRel.objects.filter(keyword_id=keyword.id)

            name = keyword.name
            priority_keyword = keyword.priority_keyword.split(",")
            keys = priority_keyword
            for m_keyword in keys:
                both_key = m_keyword.strip()
                # print(both_key)
                whole_sleep_time = random.randint(147, 360)
                for keywordcity in keywordcitys:
                    print(both_key, keywordcity.city_id.name)
                    sleep_time = random.randint(26, 76)
                    if not _check_map_record(name, both_key, keywordcity.city_id.name):
                        time.sleep(whole_sleep_time)
                        data = _get_map_record(
                            seq, name, both_key, keywordcity.city_id.name, keyword
                        )
                        if isinstance(data, list):
                            for li in data:
                                temp.append(li)
                                li.save()
                        else:
                            temp.append(data)
                            data.save()
                        time.sleep(sleep_time)
                    all_pos = all_pos + temp
                    temp = []
                
        return render(request, "keyservice/result.html", {"positions": all_pos, "error": error},)
    else:
        form = MapSearchForm()
        return render(request, "keyservice/map_search.html", {"form": form})


def get_report(request, *args, **kwargs):
    if request.method == "POST":
        form = ReportForm(request.POST)
        if form.is_valid():
            site = form.cleaned_data["site"]
            date = form.cleaned_data["date"]
            is_map = form.cleaned_data["is_map"]
            if is_map:
                filepath = _get_map_records(site, date)
            else:
                filepath = _get_search_records(site, date)
            return serve(request, os.path.basename(filepath), os.path.dirname(filepath))
    else:
        form = ReportForm()
        return render(request, "keyservice/report.html", {"form": form})


def get_graph_report(request, *args, **kwargs):
    if request.method == "POST":
        form = GraphReportForm(request.POST)
        if form.is_valid():
            site = form.cleaned_data["site"]
            interval = form.cleaned_data["interval"]
            today = datetime.today()
            # months to days conversion is months*30 days
            days = int(interval) * 30
            td = timedelta(days=days)
            start_date = today - td
            _get_graph_record(site, start_date.month, start_date.year, today.month, today.year)

            generate_graph(site)
            filepath = os.path.join(PAR_DIR, "graph.zip")
            return serve(request, os.path.basename(filepath), os.path.dirname(filepath))
    else:
        form = GraphReportForm()
        return render(request, "keyservice/graph_report.html", {"form": form})


def upload_file(request, *args, **kwargs):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES["file"]
            if not csv_file.name.endswith(".csv"):
                return render(request, "keyservice/upload.html", {"status": False})
            handle_uploaded_file(csv_file)
            return render(request, "keyservice/upload.html", {"status": True})
    else:
        form = UploadFileForm()
    return render(request, "keyservice/upload.html", {"form": form})
def upload_file_map(request, *args, **kwargs):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES["file"]
            if not csv_file.name.endswith(".csv"):
                return render(request, "keyservice/upload.html", {"status": False})
            map_upload(csv_file)
            return render(request, "keyservice/upload.html", {"status": True})
    else:
        form = UploadFileForm()
    return render(request, "keyservice/upload.html", {"form": form})


def delete_positions(request, *args, **kwargs):
    if request.method == "POST":
        positions = Position.objects.all()
        for position in positions:
            position.delete()
        return render(request, "keyservice/delete.html", {"status": False})
    else:
        return render(request, "keyservice/delete.html", {"status": True})


def get_cities(request, *args, **kwargs):
    cities = []
    site_id = request.GET.get("site_id", None)
    print(site_id)
    key_cities = KeywordCityRel.objects.filter(keyword_id__id=site_id)
    for kc in key_cities:
        cities.append(kc.city_id)
    return render(request, "keyservice/add_cities.html", {"cities": cities})


def get_last_record(request):
    site_id = request.GET.get("site_id", None)
    position = Position.objects.filter(keyword_id__id=site_id).filter(date=date.today()).last()
    return render(request, "keyservice/last_record.html", {"position": position})


def get_urls_from_keyword(request, *args, **kwargs):
    if request.POST:
        form = KeywordToUrlFrom(request.POST)
        # urls = google(request.POST.get("keyword"))
        if form.is_valid():
            url_list = google(request.POST.get("keyword"))
            data = {
                "keyword": form.cleaned_data["keyword"],
                "url_text": " \n".join(url_list),
            }
            data_form = KeywordToUrlFrom(data)
            return render(request, "keyservice/keyword_to_url.html", {"form": data_form})
            # return HttpResponse("ok")
    else:
        form = KeywordToUrlFrom()
        return render(request, "keyservice/keyword_to_url.html", {"form": form})


def test_from(request, *args, **kwargs):
    if request.method == "POST":
        img = request.FILES["image"]
        print(img)
        # form = GraphReportForm(request.POST)
        # if form.is_valid():
        #     site = form.cleaned_data["site"]
        #     interval = form.cleaned_data["interval"]
        #     print(site)
        #     print(type(interval))
        #     return HttpResponse("ok")
        return HttpResponse("failed")
    else:
        form = UploadFileForm()
        return render(request, "keyservice/test.html", {"form": form})

keyservice/templates/keyservice/action_date.html
{% extends "admin/base_site.html" %}

{% block content %}
<form action="" method="post">

    {% csrf_token %}
    <input type="hidden" name="action" value="set_date_action">
    <input type="hidden" name="do_action" value="yes">

    <div>
        {{ <form action="" class="date"></form> }}
        <input type="submit" class="default" style="float: none" value="Change">
        {{ form.genre.errors }}
    </div>

    <h2>Change date for next records</h2>

    <!-- <ul>
        {% for object in objects %}
        <li>
            <a href="{{ object.pk }}/">{{ object.title }}</a> - {{ object.genre }}
            <input type="hidden" name="_selected_action" value="{{ object.pk }}">
        </li>
        {% endfor %}
    </ul> -->

</form>
{% endblock %}

keyservice/templates/keyservice/add_cities.html
{% for city in cities %}
<li>
    <label for="{{city.name}}">
        <input type="checkbox" name="cities" value="{{city.id}}" id="{{ city.name }}">
        {{city.name}}
    </label>
</li>
{% endfor %}

keyservice/templates/keyservice/delete.html
{% extends 'base.html' %}

{% block content %}
 {% if status %}
    <form class="" action="/delete/" method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Delete">
    </form>
 {% else %}
    <p>Successfully deleted</p>
 {% endif %}
{% endblock %}

keyservice/templates/keyservice/graph_report.html
{% extends "base.html" %}
{% load static %}
{% block navigation %}
<a class="nav-link text-white bg-gradient-dark " href="/">Home </a>
<a class="nav-link text-white bg-gradient-dark" href="/search/">Find Position</a>
<a class="nav-link text-white bg-gradient-dark" href="/map-search/">Map Position </a>
<a class="nav-link text-white bg-gradient-dark" href="/report/">Report</a>
<a class="nav-link text-white bg-gradient-dark active" href="/graph-report/">Graph Report</a>
<a class="nav-link text-white bg-gradient-dark" href="/key-to-url/">Find Url</a>
{% endblock %}

{% block content %}
<div>

</div>

<form action='' method='post'>
    <fieldset class="border p-2">
        <legend>Graph Report:</legend>
        {% csrf_token %}
        {% for field in form %}
        <div class=" form-group">
            <div class="row">
                <div class="col-md-2">
                    {{ field.label_tag }}
                    {% if field.help_text %}
                    <sup>{{ field.help_text }}</sup>
                    {% endif %}
                    {{ field.errors }}
                </div>
                <div class="col-md-10 pull-left">
                    {{ field }}
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="row">
            <div class="offset-md-2">
                <input type="submit" value="generate" class="btn btn-primary" id="onclick"></div>
        </div>

    </fieldset>
</form>
{% endblock %}

{% block scriptjs %}
<script>
    // $("#onclick").click(function () {
    //     $.ajax({
    //         url: "{% url 'loading' %}",
    //         data: { "site_id": site_id },
    //         success: function () {
    //             $("#loading").html()
    //         }
    //     });
    // }); 
</script>
{% endblock %}

keyservice/templates/keyservice/index.html
{% extends "base.html" %}
{% load static %}
<!-- {% load static %} -->
{% block navigation %}
<a class="nav-link text-white bg-gradient-dark active" href="/">Home </a>
<a class="nav-link text-white bg-gradient-dark" href="/search/">Find Position</a>
<a class="nav-link text-white bg-gradient-dark" href="/map-search/">Map Position </a>
<a class="nav-link text-white bg-gradient-dark" href="/report/">Report</a>
<a class="nav-link text-white bg-gradient-dark" href="/graph-report/">Graph Report</a>
<a class="nav-link text-white bg-gradient-dark" href="/key-to-url/">Find Url</a>
{% endblock %}

{% block content %}

{% if status%}
<h4 class="p-2">Recent keyword positions of websites</h4>
<table class="table">
    <thead class="thead-light ">
        <tr>
            <th>Date</th>
            <th>URL</th>
            <th>Keywords</th>
            <th>City</th>
            <th>Position</th>
        </tr>
    </thead>
    <tbody>
        {% for position in positions %}
        <tr>
            <td>{{position.date}}</td>
            <td>{{position.url}}</td>
            <td>{{position.key}}</td>
            <td>{{position.city}}</td>
            <td>{{position.position}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<div class="m-5">
    <h2>Welcome to Desss Inc</h2>
</div>
{% endif %}

{% endblock %}

keyservice/templates/keyservice/keyword_to_url.html
{% extends 'base.html' %}
{% load static %}
<!-- {% load static %} -->
{% block navigation %}
<a class="nav-link text-white bg-gradient-dark " href="/">Home </a>
<a class="nav-link text-white bg-gradient-dark" href="/search/">Find Position</a>
<a class="nav-link text-white bg-gradient-dark" href="/map-search/">Map Position </a>
<a class="nav-link text-white bg-gradient-dark" href="/report/">Report</a>
<a class="nav-link text-white bg-gradient-dark" href="/graph-report/">Graph Report</a>
<a class="nav-link text-white bg-gradient-dark active" href="/key-to-url/">Find Url</a>
{% endblock %}


{% block content %}
<div id="form-area">
    <form method="post" action="/key-to-url/" id="urlForm">
        <fieldset class="border p-2">
            <legend>Keyword to URL</legend>
            {% csrf_token %}
            {% for field in form %}
            <div class=" form-group">
                <div class="row">
                    <div class="col-md-2">
                        {{ field.label_tag }}
                        {% if field.help_text %}
                        <sup>{{ field.help_text }}</sup>
                        {% endif %}
                        {{ field.errors }}
                    </div>
                    <div class="col-md-10 pull-left">
                        {{ field }}
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="offset-md-2">
                    <input type="submit" value="Submit" class="btn btn-primary  mr-1">
                    <input type="submit" value="Copy Text" class="btn btn-primary" onclick="copyText()">
                </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}


{% block scriptjs %}
<script>
    function copyText() {
        var urlText = document.getElementById("id_url_text")
        urlText.select()
        document.execCommand("copy")
        alert("Text Copied")
        clearText()
    }

    function clearText() {
        document.getElementById("id_keyword").value = ""
        document.getElementById("id_url_text").value = ""
    }
</script>
{% endblock %}

keyservice/templates/keyservice/last_record.html
<p>{{position}}</p>

keyservice/templates/keyservice/loading.html
{% block content %}
<div id="page-loader">
    {{job}}
    <p>Processing...</p>

</div>
{% endblock %}

keyservice/templates/keyservice/map_search.html
{% extends "base.html" %}
{% load static %}

{% block navigation %}
<a class="nav-link text-white bg-gradient-dark " href="/">Home </a>
<a class="nav-link text-white bg-gradient-dark" href="/search/">Find Position</a>
<a class="nav-link text-white bg-gradient-dark active" href="/map-search/">Map Position </a>
<a class="nav-link text-white bg-gradient-dark" href="/report/">Report</a>
<a class="nav-link text-white bg-gradient-dark" href="/graph-report/">Graph Report</a>
<a class="nav-link text-white bg-gradient-dark" href="/key-to-url/">Find Url</a>
{% endblock %}

{% block content %}

<div id="page-loader">
    <div class="centerimg">
        <img src="{% static 'images/processing.gif' %}" alt="processing" class="img-fluid">
    </div>
</div>

<div id="form-area">
    <form action='' method='post'>
        <fieldset class="border p-2">
            <legend>Map Search:</legend>
            {% csrf_token %}
            {% for field in form %}
            <div class=" form-group">
                <div class="row">
                    <div class="col-md-2">
                        {{ field.label_tag }}
                        {% if field.help_text %}
                        <sup>{{ field.help_text }}</sup>
                        {% endif %}
                        {{ field.errors }}
                    </div>
                    <div class="col-md-10 pull-left">
                        {{ field }}
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="offset-md-2">
                    <input type="submit" value="search" class="btn btn-primary" id="onclick"></div>
            </div>

        </fieldset>
    </form>
</div>
{% endblock %}

{% block scriptjs %}
<script>
    $("#onclick").click(function () {
        console.log(".....");
        $("#page-loader").css("display", "block");
        $("#form-area").css("display", "none")
    }); 
</script>
{% endblock %}

keyservice/templates/keyservice/search.html
{% extends "base.html" %}
{% load static %}

{% block navigation %}
<a class="nav-link text-white bg-gradient-dark " href="/">Home </a>
<a class="nav-link text-white bg-gradient-dark active" href="/search/">Find Position</a>
<a class="nav-link text-white bg-gradient-dark " href="/map-search/">Map Position </a>
<a class="nav-link text-white bg-gradient-dark" href="/report/">Report</a>
<a class="nav-link text-white bg-gradient-dark" href="/graph-report/">Graph Report</a>
<a class="nav-link text-white bg-gradient-dark " href="/key-to-url/">Find Url</a>
{% endblock %}

{% block content %}
<div id="page-loader">
    <div class="centerimg">
        <img src="{% static 'images/processing.gif' %}" alt="processing" class="img-fluid">
    </div>
</div>

<div id="form-area">
    <form method='post'>
        <fieldset class="border p-2">
            <legend>Organic Search:</legend>
            {% csrf_token %}
            {% for field in form %}
            <div class=" form-group">
                <div class="row">
                    <div class="col-md-2">
                        {{ field.label_tag }}
                        {% if field.help_text %}
                        <sup>{{ field.help_text }}</sup>
                        {% endif %}
                        {{ field.errors }}
                    </div>
                    <div class="col-md-10 pull-left">
                        {{ field }}
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="offset-md-2">
                    <input type="submit" value="search" class="btn btn-primary" id="onclick"></div>
            </div>

        </fieldset>
    </form>
</div>
{% endblock %}

{% block scriptjs %}
<script>
    $("#id_site").change(function () {
        const site_id = $(this).val();
        $.ajax({
            url: "{% url 'get-cities' %}",
            data: { "site_id": site_id },
            success: function (data) {
                $("#id_cities").html(data)
            }
        });
    });

    $("#onclick").click(function () {
        console.log(".....");
        $("#page-loader").css("display", "block");
        $("#form-area").css("display", "none")
    }); 
</script>
{% endblock %}

keyservice/templates/keyservice/test.html
{% extends "base.html" %}

{% block navigation %}
<a class="nav-link text-white bg-gradient-dark " href="/">Home </a>
<a class="nav-link text-white bg-gradient-dark " href="/search/">Find Position</a>
<a class="nav-link text-white bg-gradient-dark " href="/map-search/">Map Position </a>
<a class="nav-link text-white bg-gradient-dark" href="/report/">Report</a>
<a class="nav-link text-white bg-gradient-dark" href="/graph-report/">Graph Report</a>
<a class="nav-link text-white bg-gradient-dark" href="/key-to-url/">Find Url</a>
{% endblock %}

{% block content %}
<div id="loading">

</div>

<form action='' method='post' , enctype=multipart/form-data id="myform">
    {% csrf_token %}
    <input type="file" name="image" id="image">
</form>
<button id="submit-image">upload image</button>
{% endblock %}

{% block scriptjs %}
<script>
    // $("#id_site").change(function () {
    //     console.log("ajax");
    //     const site_id = $(this).val();
    //     $.ajax({
    //         url: "{% url 'get-cities' %}",
    //         data: { "site_id": site_id },
    //         success: function (data) {
    //             $("#id_cities").html(data)
    //         }
    //     });
    // });

    // $("#id_file").on('input', function () {
    //     console.log("ajax");
    //     const img = $(this).val();
    //     $.ajax({
    //         type: 'POST',
    //         url: "{% url 'barcode' %}",
    //         data: { "img": img },
    //         success: function (jsondata) {
    //             console.log(jsondata);
    //         }
    //     });
    // });

    // $("#onclick").click(function () {
    //     console.log("ajax");
    //     const img = $("#barcode").val();
    //     console.log("img", img);
    //     $.ajax({
    //         url: "{% url 'loading' %}",
    //         data: { "site_id": site_id },
    //         success: function () {
    //             $("#loading").html()
    //         }
    //     });
    // }); 

    $("#submit-image").click(function () {
        var form_data = new FormData();
        form_data.append('img', $('#myform').get(0));
        console.log($('#myform').get(0));
        $.ajax({
            url: "http://keywordpos.zunamelt.com/barcode/",
            data: form_data,
            type: "POST",
            processData: false,
            contentType: false,
            success: function (data) {
                let jdata = $.parseJSON(data);
                console.log(jdata);
                alert("success")
            },
            error: function (xhr) {
                alert(xhr.statusText)
            },
            params: {
                'csrf_token': '{{ csrf_token }}',
                'csrf_name': 'csrfmiddlewaretoken',
                'csrf_xname': 'X-CSRFToken',
            }
        });
    });

</script>
{% endblock %}

keyservice/templates/keyservice/upload.html
{% extends 'base.html' %}

{% block content %}

  {% if not status %}
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Upload</button>
    </form>
    <br>
  {% else %}
    <p>Successfully Upload</p>
  {% endif %}
{% endblock %}